"""
This type stub file was generated by pyright.
"""

from collections.abc import Iterable

"""Msgpack deserialization safety controls.

Set ``LANGGRAPH_STRICT_MSGPACK=true`` to restrict checkpoint deserialization
to the types listed in ``SAFE_MSGPACK_TYPES``.  Without this, any Python
callable stored in checkpoint data will be imported and executed on load.
"""
STRICT_MSGPACK_ENABLED = ...
_SENTINEL = ...
SAFE_MSGPACK_TYPES: frozenset[tuple[str, ...]] = ...
SAFE_MSGPACK_METHODS: frozenset[tuple[str, str, str]] = ...
AllowedMsgpackModules = Iterable[tuple[str, ...] | type]
