"""
This type stub file was generated by pyright.
"""

from typing import Any
from langgraph.checkpoint.serde.base import CipherProtocol, SerializerProtocol

class EncryptedSerializer(SerializerProtocol):
    """Serializer that encrypts and decrypts data using an encryption protocol."""
    def __init__(self, cipher: CipherProtocol, serde: SerializerProtocol = ...) -> None:
        ...
    
    def dumps_typed(self, obj: Any) -> tuple[str, bytes]:
        """Serialize an object to a tuple `(type, bytes)` and encrypt the bytes."""
        ...
    
    def loads_typed(self, data: tuple[str, bytes]) -> Any:
        ...
    
    @classmethod
    def from_pycryptodome_aes(cls, serde: SerializerProtocol = ..., **kwargs: Any) -> EncryptedSerializer:
        """Create an `EncryptedSerializer` using AES encryption."""
        class PycryptodomeAesCipher(CipherProtocol):
            ...
        
        
    


