"""
This type stub file was generated by pyright.
"""

from collections.abc import Callable
from typing import TypedDict
from typing_extensions import NotRequired

logger = ...
class SerdeEvent(TypedDict):
    kind: str
    module: str
    name: str
    method: NotRequired[str]
    ...


SerdeEventListener = Callable[[SerdeEvent], None]
_listeners: list[SerdeEventListener] = ...
_listeners_lock = ...
def register_serde_event_listener(listener: SerdeEventListener) -> Callable[[], None]:
    """Register a listener for serde allowlist events."""
    ...

def emit_serde_event(event: SerdeEvent) -> None:
    """Emit a serde event to all listeners.

    Listener failures are isolated and logged.
    """
    ...

