"""
This type stub file was generated by pyright.
"""

from typing import TYPE_CHECKING
from langchain_core.runnables import RunnableConfig
from langgraph.checkpoint.base import BaseCheckpointSaver, CheckpointTuple

"""Replay state for subgraph checkpoint loading during time-travel."""
if TYPE_CHECKING:
    ...
class ReplayState:
    """Tracks which subgraphs have already loaded their pre-replay checkpoint.

    During a parent replay, each subgraph's first invocation should restore the
    checkpoint from before the replay point. Subsequent invocations of the same
    subgraph (e.g. in a loop) should use normal checkpoint loading so they pick
    up freshly created checkpoints.

    The single `ReplayState` instance is shared by reference across all derived
    configs within one parent execution.
    """
    __slots__ = ...
    def __init__(self, checkpoint_id: str) -> None:
        ...
    
    def get_checkpoint(self, checkpoint_ns: str, checkpointer: BaseCheckpointSaver, checkpoint_config: RunnableConfig) -> CheckpointTuple | None:
        """Load the right checkpoint for a subgraph during replay.

        On the first call for a given subgraph namespace, returns the latest
        checkpoint created *before* the replay point. On subsequent calls
        (e.g. the same subgraph in a later loop iteration), falls back to
        normal latest-checkpoint loading.
        """
        ...
    
    async def aget_checkpoint(self, checkpoint_ns: str, checkpointer: BaseCheckpointSaver, checkpoint_config: RunnableConfig) -> CheckpointTuple | None:
        """Async version of `get_checkpoint`."""
        ...
    


