"""
This type stub file was generated by pyright.
"""

from collections.abc import Sequence
from dataclasses import dataclass
from typing import Any, Literal, TypeAlias, TypeVar
from uuid import UUID
from langchain_core.callbacks import BaseCallbackHandler, BaseCallbackManager
from langchain_core.runnables import RunnableConfig
from langgraph.types import Interrupt

"""Graph lifecycle callback interfaces and event payloads.

This module defines the public callback surface for observing LangGraph-specific
lifecycle transitions such as interrupt and resume.
"""
__all__ = ("GraphCallbackHandler", "GraphInterruptEvent", "GraphLifecycleEvent", "GraphLifecycleStatus", "GraphResumeEvent", "get_async_graph_callback_manager_for_config", "get_sync_graph_callback_manager_for_config")
GraphLifecycleStatus: TypeAlias = Literal["input", "pending", "done", "interrupt_before", "interrupt_after", "out_of_steps",]
@dataclass(frozen=True)
class GraphInterruptEvent:
    """Graph lifecycle event emitted when execution pauses for interrupts."""
    run_id: UUID | None
    status: GraphLifecycleStatus
    checkpoint_id: str
    checkpoint_ns: tuple[str, ...]
    interrupts: tuple[Interrupt, ...]
    ...


@dataclass(frozen=True)
class GraphResumeEvent:
    """Graph lifecycle event emitted when execution resumes from a checkpoint."""
    run_id: UUID | None
    status: GraphLifecycleStatus
    checkpoint_id: str
    checkpoint_ns: tuple[str, ...]
    ...


GraphLifecycleEvent: TypeAlias = GraphInterruptEvent | GraphResumeEvent
class GraphCallbackHandler(BaseCallbackHandler):
    """Base class for graph-level lifecycle callbacks.

    Subclass this handler to observe graph lifecycle transitions that are
    specific to LangGraph execution, rather than generic LangChain runnable
    callbacks.

    Instances can be passed through `config["callbacks"]` when invoking a
    graph. Only handlers that inherit from `GraphCallbackHandler` receive these
    lifecycle events.
    """
    def on_interrupt(self, event: GraphInterruptEvent) -> Any:
        """Run when graph execution pauses due to one or more interrupts.

        Args:
            event: Interrupt lifecycle event payload.
        """
        ...
    
    def on_resume(self, event: GraphResumeEvent) -> Any:
        """Run when graph execution resumes from a persisted checkpoint.

        Args:
            event: Resume lifecycle event payload.
        """
        ...
    


_MISSING = ...
class _GraphCallbackManager(BaseCallbackManager):
    """Sync dispatcher for graph lifecycle events."""
    run_id: UUID | None
    def __init__(self, handlers: Sequence[GraphCallbackHandler] | None = ..., inheritable_handlers: Sequence[GraphCallbackHandler] | None = ..., parent_run_id: UUID | None = ..., *, tags: list[str] | None = ..., inheritable_tags: list[str] | None = ..., metadata: dict[str, Any] | None = ..., inheritable_metadata: dict[str, Any] | None = ..., run_id: UUID | None = ...) -> None:
        ...
    
    def copy(self, *, run_id: UUID | None | object = ...) -> _GraphCallbackManager:
        ...
    
    @classmethod
    def configure(cls, callbacks: object | None = ..., *, run_id: UUID | None = ...) -> _GraphCallbackManager:
        ...
    
    def on_interrupt(self, event: GraphInterruptEvent) -> None:
        ...
    
    def on_resume(self, event: GraphResumeEvent) -> None:
        ...
    


class _AsyncGraphCallbackManager(BaseCallbackManager):
    """Async dispatcher for graph lifecycle events."""
    run_id: UUID | None
    @property
    def is_async(self) -> bool:
        """Return whether the manager is async."""
        ...
    
    def __init__(self, handlers: Sequence[GraphCallbackHandler] | None = ..., inheritable_handlers: Sequence[GraphCallbackHandler] | None = ..., parent_run_id: UUID | None = ..., *, tags: list[str] | None = ..., inheritable_tags: list[str] | None = ..., metadata: dict[str, Any] | None = ..., inheritable_metadata: dict[str, Any] | None = ..., run_id: UUID | None = ...) -> None:
        ...
    
    def copy(self, *, run_id: UUID | None | object = ...) -> _AsyncGraphCallbackManager:
        ...
    
    @classmethod
    def configure(cls, callbacks: object | None = ..., *, run_id: UUID | None = ...) -> _AsyncGraphCallbackManager:
        ...
    
    async def on_interrupt(self, event: GraphInterruptEvent) -> None:
        ...
    
    async def on_resume(self, event: GraphResumeEvent) -> None:
        ...
    


_GraphManagerT = TypeVar("_GraphManagerT", _GraphCallbackManager, _AsyncGraphCallbackManager)
GraphCallbacks: TypeAlias = (_GraphCallbackManager | _AsyncGraphCallbackManager | BaseCallbackManager | GraphCallbackHandler | Sequence[BaseCallbackHandler] | Sequence[GraphCallbackHandler] | None)
def get_sync_graph_callback_manager_for_config(config: RunnableConfig, *, run_id: UUID | None = ...) -> _GraphCallbackManager:
    """Build a sync graph lifecycle callback manager from a runnable config.

    This helper filters `config["callbacks"]` down to handlers that inherit
    from `GraphCallbackHandler` and binds the provided `run_id` onto the
    returned manager.
    """
    ...

def get_async_graph_callback_manager_for_config(config: RunnableConfig, *, run_id: UUID | None = ...) -> _AsyncGraphCallbackManager:
    """Build an async graph lifecycle callback manager from a runnable config.

    This helper filters `config["callbacks"]` down to handlers that inherit
    from `GraphCallbackHandler` and binds the provided `run_id` onto the
    returned manager.
    """
    ...

